/** Every @theme variable the package's components rely on. */
export const TOKENS = [
  '--color-primary',
  '--color-primary-contrast',
  '--color-surface',
  '--color-on-surface',
  '--color-muted',
  '--radius-card',
  '--shadow-raised',
  '--duration-expand',
  '--color-backdrop',
  '--color-focus',
  '--richtext-flow',
  '--richtext-measure',
  '--richtext-h1',
  '--richtext-h2',
  '--richtext-h3',
  '--richtext-h4',
  '--heading-1',
  '--heading-2',
  '--heading-3',
  '--heading-4',
] as const
