/** Every @theme variable the package's components rely on. */
export const TOKENS = [
  '--color-primary',
  '--color-primary-contrast',
  '--color-surface',
  '--color-on-surface',
  '--color-muted',
  '--radius-card',
  '--shadow-raised',
  '--duration-expand',
  '--color-backdrop',
  '--color-focus',
  '--richtext-flow',
  '--richtext-measure',
  '--richtext-h1',
  '--richtext-h2',
  '--richtext-h3',
  '--richtext-h4',
  '--heading-1',
  '--heading-2',
  '--heading-3',
  '--heading-4',
  '--carousel-dot',
  '--carousel-dot-active',
  '--color-error',
  '--field-accent',
  '--color-background',
  '--color-foreground',
  '--color-primary-foreground',
  '--color-card',
  '--color-card-foreground',
  '--color-muted-foreground',
  '--color-border',
  '--color-input',
  '--color-ring',
  '--color-destructive',
  '--color-accent',
  '--color-accent-foreground',
] as const

/** Deprecated name → its replacement. The replacement defaults to `var(<old>)`
    until 1.0 removes the old name. */
export const DEPRECATED_TOKENS = {
  '--color-primary-contrast': '--color-primary-foreground',
  '--color-surface': '--color-card',
  '--color-on-surface': '--color-card-foreground',
  '--color-muted': '--color-muted-foreground',
  '--color-focus': '--color-ring',
  '--color-error': '--color-destructive',
} as const
